### ISSUE TITLE
latent graph structure - Encoder.forward()

### ISSUE THREAD

**Issue by mishooax** [openclimatefix/graph_weather#44]
@jacobbieker  - Hi, I've been looking at the GNN encoder / decoder code to try to understand the overall logic and structure (I'm new to pytorch-geometric). I'm not quite able to unpack the following snippet https://github.com/openclimatefix/graph_weather/blob/main/graph_weather/models/layers/encoder.py#L179:

```python
out = einops.rearrange(out, "b n f -> (b n) f")
return (
            out,
            torch.cat(
                [self.latent_graph.edge_index + i * torch.max(self.latent_graph.edge_index) + i for i in range(batch_size)],
                dim=1,
            ),
            self.latent_edge_encoder(einops.repeat(self.latent_graph.edge_attr, "e f -> (repeat e) f", repeat=batch_size)),
        )  # New graph
```

Judging by the comment, this builds the structure of the "new" latent graph (with updated node and edge info). Why are the edge indexes and edge attribute tensors concatenated / repeated this way, though? Thanks!

**Comment by jacobbieker** [comment]
Hi, sorry for the delay, was on annual leave. For the repeating of the indicies and attributes, its repeating the latent graph to match the batch size of the input. So that each input example has its own copy of the latent graph. 

For the second point, yeah, its to allow the GNN to learn its own weighting of the different nodes. It probably should be defined as a `nn.Parameter`, I think this tensor would still learn and get updated on the backwards pass as the model trains, but yeah, probably more clear to wrap it in a `Parameter`.

**Comment by peterdudfield** [comment]
@all-contributors please add @mishooax  for question
